version: '3.8'

services:
  backend:
    container_name: forum_backend_dev
    build:
      context: ./backend/.
      target: development
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env # Path to your .env file
    depends_on:
      - mongo_db
      - redis
    command: npm run dev

  mongo_db:
    image: mongo
    container_name: your-cont-name
    command: mongod
    volumes:
      - mongodbdata:/data/db

  redis:
    container_name: forum_redis_dev
    image: redis:latest
    ports:
      - '6379:6379'

networks:
  default:
    external:
      name: backend_network

volumes:
  mongodbdata:
    driver: local
