version: '3.8'

services:
  backend:
    build:
      context: ../backend/.
      target: development
    ports:
      - '4000:4000'
    env_file: ../backend/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://root:example@mongo:27017/forum?authSource=admin
    depends_on:
      - mongo
      - redis
      - mongo-express
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    command: npm run dev
  app:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../:/frontend
    ports:
      - '3000:3000'
    image: frontend:latest
    container_name: frontend_container
    command: npm start

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
