name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URI_TESTS: ${{ vars.DB_URI_TESTS }}
      TESTS_CACHE_URL: ${{ vars.TESTS_CACHE_URL }}
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          echo "DB_URI_TESTS: $DB_URI_TESTS"
          echo "TESTS_CACHE_URL: $TESTS_CACHE_URL"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./backend/package-lock.json

      - run: yarn install

      - name: Generate Coverage
        run: |
          export DB_URI_TESTS=mongodb+srv://andrewkarma:3ff09d2A!@cluster0.frqlxhe.mongodb.net/?retryWrites=true&w=majority
          export TESTS_CACHE_URL=redis://default:m9brEOnVSWkNNED7PQ3s2pvaVSaLXWnS@redis-12980.c135.eu-central-1-1.ec2.cloud.redislabs.com:12980
          yarn test
      - run: npm run ready --if-present
