# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URI_TESTS: ${{ github.DB_URI_TESTS }}
      TESTS_CACHE_URL: ${{ github.TESTS_CACHE_URL }}
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./backend/package-lock.json

      - run: npm i

      - name: Create env file
        run: |
          touch .env
          echo TESTS_CACHE_URL=${{ vars.TESTS_CACHE_URL }} >> .env
          echo DB_URI_TESTS=${{ vars.DB_URI_TESTS }} >> .env
          echo "cat .env"
          cat.env
          ls -a .
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      - run: npm run ready --if-present
      - run: npm run test:ci
