name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      ENV_VAR_1: ${{ secrets.REDIS_URL }}
      ENV_VAR_2: ${{ secrets.TESTS_CACHE_URL }}
      ENV_VAR_3: ${{secrets.DB_URI_TESTS}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Create .env with Github Secrets and run script
        run: |
          touch .env
          echo REDIS_URL=$ENV_VAR_1 >> .env
          echo TESTS_CACHE_URL=$ENV_VAR_2 >> .env
          echo DB_URI_TESTS=$ENV_VAR_3 >> .env
          npm run test
        env:
          ENV_VAR_1: ${{ secrets.REDIS_URL }}
          ENV_VAR_2: ${{ secrets.TESTS_CACHE_URL }}
          ENV_VAR_3: ${{secrets.DB_URI_TESTS}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./backend/package-lock.json

      - run: yarn install

      - name: Generate Coverage
        run: yarn test
      - run: npm run ready --if-present
      - name: Generate Coverage
        run: yarn test
